Gsoc3
JiaoJiao123/igv.js pull request #5
Opened 2017-06-20 09:34 UTC by Ishu-Kalra

2017-06-20 18:22 UTC, JiaoJiao123 requested changes

2017-06-20 18:22 UTC, JiaoJiao123 commented on js/igv-create.js
> +         }
There are loopholes in this logic. We don't always change it to lowercase.  For example, What if user entered chrx? To avoid 'unrecognized locus', we need to change it to chrX. 
Please use regular expression for string match instead.
if (/^chr[x|y]$/i.test(text)) {
     config.locus = "chr" + config.locus.toUpperCase();
} else {
     config.locus  = config.locus.toLowerCase();
}

2017-06-20 18:22 UTC, JiaoJiao123 commented on js/igv-create.js
> +              var result = $(e.target).val();
why do you need to do the check that is duplicated to above? could you double check if it necessary?

2017-06-20 18:22 UTC, JiaoJiao123 commented on js/viewport.js
> +                  arrX[i]=arrX[i-1] + arrX[i];
It is not a good practice to write code like this since you are doing unnecessary if condition check every time.
move line 319 out of for loop, and start i from 1. Remember to push the first value to arrX

2017-06-20 18:22 UTC, JiaoJiao123 commented on js/viewport.js
> +                {
keep the format unified. use 4 space indention in every place

2017-06-21 10:26 UTC, Ishu-Kalra commented on js/igv-create.js
> +              var result = $(e.target).val();
Yeah, I think It is necessary since I can not change $(e.target).val() in the code lines below. So I used result instead.

2017-06-21 14:38 UTC, merged